llm:
  provider: OLLAMA

  meta:
    model: codellama:7b
    max_tokens: 2048
    temperature: 0.2

  http_client:
    timeout: 120
    api_url: http://localhost:11434

vcs:
  provider: GITLAB
  http_client:
    timeout: 120

prompt:
  inline_prompt_files: [ ./prompts/inline.md ]
  context_prompt_files: [ ./prompts/inline.md ]
  
artifacts:
  llm_dir: ./artifacts/llm
  llm_enabled: true

review:
  allow_changes: ["*.cpp"]