.ai-review-base:
  when: manual
  variables:
    VCS__PIPELINE__PROJECT_ID: "$CI_PROJECT_ID"
    VCS__HTTP_CLIENT__API_URL: "$CI_SERVER_URL"
    VCS__HTTP_CLIENT__API_TOKEN: "$CI_API_VLE_SOLVERS_TOKEN"
  artifacts:
    when: always
    paths: [ artifacts/llm/*.json ]
    expire_in: 3 days
  allow_failure: true

.ai-review-all:
  script:
    - |
      API_URL="${CI_SERVER_URL}/api/v4/projects/${CI_PROJECT_ID}/repository/commits/${CI_COMMIT_SHA}/merge_requests"

      # Выполняем запрос к API
      RESPONSE=$(curl --silent --header "PRIVATE-TOKEN: ${CI_API_VLE_SOLVERS_TOKEN}" "$API_URL")

      # Извлекаем IID первого найденного MR (предполагаем, что он один)
      export VCS__PIPELINE__MERGE_REQUEST_ID=$(echo "$RESPONSE" | grep -o '"iid":[0-9]*' | head -1 | sed 's/"iid"://')
    - ai-review show-config
    - ai-review run
  extends: .ai-review-base

.ai-review-inline:
  script:
    - ai-review show-config
    - ai-review run-inline
  extends: .ai-review-base

.ai-review-context:
  script:
    - ai-review show-config
    - ai-review run-context
  extends: .ai-review-base

.ai-review-summary:
  script:
    - ai-review show-config
    - ai-review run-summary
  extends: .ai-review-base

.ai-review-inline-reply:
  script:
    - ai-review show-config
    - ai-review run-inline-reply
  extends: .ai-review-base

.ai-review-summary-reply:
  script:
    - ai-review show-config
    - ai-review run-summary-reply
  extends: .ai-review-base

.ai-review-clear-inline:
  script:
    - ai-review show-config
    - ai-review clear-inline
  extends: .ai-review-base

.ai-review-clear-summary:
  script:
    - ai-review show-config
    - ai-review clear-summary
  extends: .ai-review-base